# Generated by Django 3.0.8 on 2020-07-18 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='part',
            name='manufacturer_index',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='part',
            name='producer',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='part',
            name='product_series',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='part',
            name='description',
            field=models.CharField(blank=True, help_text='Part description', max_length=250),
        ),
    ]
