# Generated by Django 3.0.8 on 2020-07-18 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20200718_0344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockitem',
            name='part',
            field=models.ForeignKey(help_text='Base part', on_delete=django.db.models.deletion.CASCADE, related_name='stock_items', to='inventory.Part', verbose_name='Base Part'),
        ),
    ]
